sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HBoKGYtCdog3ks40KMykp3fHy74cL7F+24PEpB3l7zFqYt7fJwi9ckiPDAYUZmCKSM03Fok4VXQ5fWHF1dBQGq9FRt8uxJthsj5z2jsQBw/e0Lc2UNk1z6ys+cNPmhoPq33WKDqLhmppLz8B//0kJ+l7WAyjboRw95eBtwgHDK9AwjqoyMQs79ccI3gaoTavAYm1Gf1SVrZ2z9Eqcq3JJWM4W8n5jbvlosH4yT9BjyrJGtZnczBgKJm7RrrVuQx1VhwvxUAfcy/iiz5ugBtmwfdRZgQf2vpHN6Jg7tE/gh5hQIji9iuBxXXbX8+Eb5/B1Clc0xa+O6NlV0tB3wRhf9Kdq+RKWrMVr0Uf3yyFmZgZwyFIcLCqsHHb+BqoeCbYBKP6XYYeHgwcHl+EL5SALcSOFph6Gzf6traRY9ElEjwh5iiGG5AydnCCj7LTt4vTkYIA1Z4rvtswdSbOOWnO0+lxFYhCIOrZRY1HX5NBOSUoKIWwMUWSg9j5fnLgejv1hF8FYkp5EWtgQ6yMAM9BqsRNwBT0tSeW2IwSimUcg+vYLXOw4rULfXnnlqFaa4ppwyp6LCg+C78mobOmc13UYgLMPgaABmoUCCIvwQ//xfVxpg8bCeSfFuPenvroz3sZYFtO6UXQkQyDIdWNrUadSMS4iBOWX4zbubQHLkVqqf8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Zeppelin-s-Passenger_1931
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy